"""create_initial_schema

Revision ID: e733e23ae7a1
Revises: 
Create Date: 2026-05-06 15:55:41.490016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e733e23ae7a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competenze',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('fasi_standard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_nome', sa.String(length=80), nullable=False),
    sa.Column('fase_nome', sa.String(length=80), nullable=False),
    sa.Column('ordine', sa.SmallInteger(), nullable=False),
    sa.Column('percentuale_ore', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruoli',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('dipendenti',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('profilo', sa.String(length=60), nullable=False),
    sa.Column('ruolo_id', sa.Integer(), nullable=True),
    sa.Column('ore_sett', sa.SmallInteger(), nullable=False),
    sa.Column('costo_ora', sa.Float(), nullable=True),
    sa.Column('competenze', sa.JSON(), nullable=True),
    sa.Column('sede', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('data_assunzione', sa.Date(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ruolo_id'], ['ruoli.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dipendenti_competenze',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=False),
    sa.Column('competenza_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competenza_id'], ['competenze.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dipendente_id', 'competenza_id', name='uq_dip_comp')
    )
    op.create_table('presenze_settimanali',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=False),
    sa.Column('settimana', sa.Date(), nullable=False),
    sa.Column('giorni_sede', sa.SmallInteger(), nullable=True),
    sa.Column('giorni_remoto', sa.SmallInteger(), nullable=True),
    sa.Column('ore_assenza', sa.Float(), nullable=True),
    sa.Column('tipo_assenza', sa.String(length=60), nullable=True),
    sa.Column('nota_assenza', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dipendente_id', 'settimana', name='uq_presenza')
    )
    op.create_table('progetti',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=True),
    sa.Column('stato', sa.String(length=30), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('priorita', sa.String(length=10), nullable=False),
    sa.Column('ritardabilita', sa.String(length=10), nullable=True),
    sa.Column('data_inizio', sa.Date(), nullable=True),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('budget_ore', sa.Integer(), nullable=True),
    sa.Column('giornate_vendute', sa.Float(), nullable=True),
    sa.Column('valore_contratto', sa.Float(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('fase_corrente', sa.String(length=80), nullable=True),
    sa.Column('sede', sa.String(length=40), nullable=True),
    sa.Column('pm_id', sa.String(length=10), nullable=True),
    sa.Column('scadenza_bando', sa.Date(), nullable=True),
    sa.Column('motivo_sospensione', sa.Text(), nullable=True),
    sa.Column('lezioni_apprese', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pm_id'], ['dipendenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('ruolo_app', sa.String(length=20), nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fasi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('progetto_id', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordine', sa.SmallInteger(), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=True),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('ore_vendute', sa.Float(), nullable=True),
    sa.Column('ore_pianificate', sa.Float(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_progetto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('progetto_id', sa.String(length=10), nullable=False),
    sa.Column('autore_id', sa.String(length=10), nullable=True),
    sa.Column('titolo', sa.String(length=200), nullable=True),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autore_id'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pianificazioni_bozza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('progetto_id', sa.String(length=10), nullable=False),
    sa.Column('dati_json', sa.JSON(), nullable=False),
    sa.Column('creato_da', sa.String(length=10), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creato_da'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segnalazioni',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('priorita', sa.String(length=10), nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=True),
    sa.Column('progetto_id', sa.String(length=10), nullable=True),
    sa.Column('dettaglio', sa.Text(), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spese',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=False),
    sa.Column('settimana', sa.Date(), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('progetto_id', sa.String(length=10), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segnalazione_id', sa.String(length=10), nullable=True),
    sa.Column('opzione_scelta', sa.String(length=10), nullable=True),
    sa.Column('descrizione_opzione', sa.Text(), nullable=True),
    sa.Column('azioni_applicate', sa.JSON(), nullable=True),
    sa.Column('approvato_da', sa.String(length=10), nullable=True),
    sa.Column('esito', sa.String(length=40), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approvato_da'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['segnalazione_id'], ['segnalazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('progetto_id', sa.String(length=10), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('fase', sa.String(length=60), nullable=True),
    sa.Column('ore_stimate', sa.Integer(), nullable=True),
    sa.Column('ore_consumate', sa.Float(), nullable=True),
    sa.Column('ore_rimanenti', sa.Float(), nullable=True),
    sa.Column('ore_pianificate', sa.Float(), nullable=True),
    sa.Column('data_inizio', sa.Date(), nullable=True),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('motivo_blocco', sa.Text(), nullable=True),
    sa.Column('profilo_richiesto', sa.String(length=60), nullable=True),
    sa.Column('predecessore', sa.String(length=10), nullable=True),
    sa.Column('ordine', sa.SmallInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dipendente_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['fasi.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['progetto_id'], ['progetti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assegnazioni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=10), nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=False),
    sa.Column('ore_assegnate', sa.Integer(), nullable=True),
    sa.Column('ruolo', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'dipendente_id', name='uq_assegnazione')
    )
    op.create_table('consuntivi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=10), nullable=False),
    sa.Column('dipendente_id', sa.String(length=10), nullable=False),
    sa.Column('settimana', sa.Date(), nullable=False),
    sa.Column('ore_dichiarate', sa.Float(), nullable=False),
    sa.Column('compilato', sa.Boolean(), nullable=False),
    sa.Column('data_compilazione', sa.DateTime(), nullable=True),
    sa.Column('modalita', sa.String(length=10), nullable=True),
    sa.Column('motivo_fermo', sa.String(length=120), nullable=True),
    sa.Column('sottotask_nota', sa.Text(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_id'], ['dipendenti.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'dipendente_id', 'settimana', name='uq_consuntivo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consuntivi')
    op.drop_table('assegnazioni')
    op.drop_table('task')
    op.drop_table('interventi')
    op.drop_table('spese')
    op.drop_table('segnalazioni')
    op.drop_table('pianificazioni_bozza')
    op.drop_table('note_progetto')
    op.drop_table('fasi')
    op.drop_table('utenti')
    op.drop_table('progetti')
    op.drop_table('presenze_settimanali')
    op.drop_table('dipendenti_competenze')
    op.drop_table('dipendenti')
    op.drop_table('ruoli')
    op.drop_table('fasi_standard')
    op.drop_table('competenze')
    # ### end Alembic commands ###
